global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: transaction-api
    metrics_path: /metrics
    static_configs:
      - targets: ["transaction-api:8000"]

  - job_name: detector
    static_configs:
      - targets: ["detector:9101"]

  - job_name: decision-store
    static_configs:
      - targets: ["decision-store:9102"]

  - job_name: alerter
    static_configs:
      - targets: ["alerter:9103"]

